name: Build
on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Recreate README.md
        uses: terraform-docs/gh-action@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          # config-file: .terraform-docs.yml
          git-push: true
          git-push-sign-off: true