name: Build
on:
  push:
    branches:
      - "main"
jobs:
  build:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Recreate README.md
        uses: terraform-docs/gh-actions@18dc76d9b2e3c746cf6f8e073c7fa7df16dcf620
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          # config-file: .terraform-docs.yml
          git-push: true
          git-push-sign-off: true